name = "hello"
description = ""
version = "0.1.0-dev"

authors = ["Khongchai"]
maintainers = ["Khongchai <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
